services:
  - type: web
    name: ABDI-
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python -m ml.train_model
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
